### PR TITLE
v6.0.0-beta1

### PR DESCRIPTION
**Pull request by crftwrk**
@justinkruit Created this branch where we should add commits/PR's for the v6 release without asking for a review (except critical stuff) to speed this up. Review then in the final PR. Agree?

- Closes https://github.com/bootscore/bootscore/issues/367
- Closes https://github.com/bootscore/bootscore/issues/693
- Closes https://github.com/bootscore/bootscore/issues/692
- Closes https://github.com/bootscore/bootscore/issues/631
- Closes https://github.com/bootscore/bootscore/issues/687
- Closes https://github.com/bootscore/bootscore/issues/621
- Closes https://github.com/bootscore/bootscore/issues/532

#### PR's

- https://github.com/bootscore/bootscore/pull/696
- https://github.com/bootscore/bootscore/pull/697
- https://github.com/bootscore/bootscore/pull/698
- https://github.com/bootscore/bootscore/pull/699
- https://github.com/bootscore/bootscore/pull/700
- https://github.com/bootscore/bootscore/pull/701
- https://github.com/bootscore/bootscore/pull/702
- https://github.com/bootscore/bootscore/pull/704
- https://github.com/bootscore/bootscore/pull/705
- https://github.com/bootscore/bootscore/pull/707
- https://github.com/bootscore/bootscore/pull/708
- https://github.com/bootscore/bootscore/pull/709
- https://github.com/bootscore/bootscore/pull/703
- https://github.com/bootscore/bootscore/pull/710
- https://github.com/bootscore/bootscore/pull/711
- https://github.com/bootscore/bootscore/pull/712
- https://github.com/bootscore/bootscore/pull/713
- https://github.com/bootscore/bootscore/pull/717
- https://github.com/bootscore/bootscore/pull/718
- https://github.com/bootscore/bootscore/pull/719
- https://github.com/bootscore/bootscore/pull/720
- https://github.com/bootscore/bootscore/pull/721
- https://github.com/bootscore/bootscore/pull/722
- https://github.com/bootscore/bootscore/pull/723
- https://github.com/bootscore/bootscore/pull/726
- https://github.com/bootscore/bootscore/pull/728
- https://github.com/bootscore/bootscore/pull/729
- https://github.com/bootscore/bootscore/pull/732
- https://github.com/bootscore/bootscore/pull/733
- https://github.com/bootscore/bootscore/pull/734
- https://github.com/bootscore/bootscore/pull/737
- https://github.com/bootscore/bootscore/pull/739
- https://github.com/bootscore/bootscore/pull/740
- https://github.com/bootscore/bootscore/pull/741
- https://github.com/bootscore/bootscore/pull/742
- https://github.com/bootscore/bootscore/pull/743
- https://github.com/bootscore/bootscore/pull/745
- https://github.com/bootscore/bootscore/pull/754
- https://github.com/bootscore/bootscore/pull/756

### CODE REVIEW

**Comment by justinkruit** [comment]
For our situation it can be done, as we can both make changes to the PR. Normally this isn't the best way because only people with the correct permissions can edit the v6 branch and add commits to the PR.

**Comment by crftwrk** [comment]
Yes, this is true. But I'm not talking about months, I'm talking about days. The todo list for v6 is very long and if we merge each commit to main branch we can do release in spring 2027. If there is a PR to main branch we can simply merge it to here. The plan is to create a quick preview of v6. If it's good we can merge, if not I start from scratch again.

**Comment by justinkruit** [comment]
Are you alright with me first checking the filter PRs?

**Comment by crftwrk** [comment]
> Are you alright with me first checking the filter PRs?

Yes, I'm alright. Those filters are amazing ;-)

Created a new site with sample content where you can check quickly each template https://projekte.crftwrk.de/boilerplate-sample-content/

The main features of this PR:

- Fine-tuned spacer classes
- Deny direct access
- Jumbotron to index
- More filters
- Refactored header to sticky-top
- Thanks to sticky-top, there is a new top-bar widget area which is good to show an important note, a coupon or whatever you want. This widget has no classes, plain HTML should be used in widget content.

**Comment by crftwrk** [comment]
From my side [v6 branch](https://github.com/bootscore/bootscore/tree/v6.0.0-beta1) is now ready to review/test, have no further changes for now. Created a new [site with sample content](https://projekte.crftwrk.de/boilerplate-sample-content/) to check the entire theme.

v6 branch [child theme](https://github.com/bootscore/bootscore-child/tree/v6) 

I think we should go this way:

- I need at least 2 more weeks for the docs part, so there is enough time to test.
- Deep check for potential breaking changes such as renaming/moving critical files/functions/filters and fix them now.
- Release a 6.0.0-beta1 (with option of beta2), waiting for users feedback and minor bugfixes.
- All new releases without `-main` branch suffix in theme folder name.
- Release 6 stable and include an auto-updater. @smileBeda It would be great if you come in here. How the release tags should look like that they work with your script https://github.com/orgs/bootscore/discussions/603?

I have this installed already on a small client's shop and seems to work well. Let me know what you think.

**Comment by smileBeda** [comment]
Release tag should be as per server/php versioning:
`major.minor.patch`

There should be no prefixes or suffixes.
So, a valid tag would be `1.0.0` and then, assuming we do another release with a tiny bugfix, it would be `1.0.1` and if instead its a major version, `2.0.0` or if it is a non-breaking new feature `1.1.0` for example

In short, numbers only, separated by dots. The numbers themselves of course can be any between 0 and n (so, 1.99.0 is just as OK as `1.0.1818181`)

_Keep in mind that `1.0.10` is _lower_ than `1.1.0`, and _higher_ than `1.0.9` or `1.0.1`_

---

I will see to find time to test V6 with the updater as well, since I can see how #603 still has some todo I never got to :(
I think they are all obsolete by now, but just to make sure.

**Comment by justinkruit** [comment]
> There should be no prefixes or suffixes.

Actually this allowed on both PHP and Semantic Versioning 2.0.0.
https://semver.org/#spec-item-9
[https://www.php.net/manual/en/function.version-compare.php](https://www.php.net/manual/en/function.version-compare.php#:~:text=The%20function%20first,containing%20development%20state.)

**Review by justinkruit — APPROVED** [review]
Time for the big beta 🎉

**Pull request merged**
