### PR TITLE
Update both standard and WC breadcrumbs to match bootstrap 5.2 syntax

### PR DESCRIPTION
**Pull request by sean-au**
Breadrumbs can now be styles as per guidance on the bootstrap 5.2 docs

https://getbootstrap.com/docs/5.2/components/breadcrumb/

The divider is styled through CSS

### CODE REVIEW

**Comment by justinkruit** [comment]
Any reason you closed the PR again?

**Comment by sean-au** [comment]
Hi I compared main by mistake, I submitted again with a branch

**Comment by sean-au** [comment]
sorry actually don't I fixed up main there's nothing there!

**Comment by sean-au** [comment]
For some reason the branch PR did not go through. If you want you can re
open this one

**Comment by crftwrk** [comment]
It is already merged https://github.com/bootscore/bootscore/pull/274

**Pull request closed without merging**
