### PR TITLE
Add bootscore_container_class() function

### PR DESCRIPTION
**Pull request by sweetappleuk**
Allows you to optionally create fluid layouts.

If constant BOOTSCORE_CONTAINER_FLUID is true, the  'container-fluid' class is output in all current templates

### CODE REVIEW

**Comment by sweetappleuk** [comment]
The reason for using the constant was so that people would have to very deliberately choose to use fluid layouts. If it's made too "easy", then the project maintainers are likely to get more complaints that the default styling looks odd on fluid layouts and hence creates more work...

But if you'd prefer it's made pluggable I'm happy to do that.

**Comment by sweetappleuk** [comment]
Refactored to be pluggable as requested.

If that's ok will create a pull request for bs-loop-templates

**Review by crftwrk — DISMISSED** [review]
I'm in 👍

2 spaces instead 4 for formatting would be nice

```php
if( ! function_exists('bootscore_container_class') ) {
  function bootscore_container_class() {
    return "container";
  }
}
```

**Review by crftwrk — APPROVED** [review]

**Review by justinkruit — APPROVED** [review]

**Comment by crftwrk** [comment]
https://bootscore.me/documentation/fluid-layout/

**Pull request merged**
