### PR TITLE
Reduce WC templates 7

### PR DESCRIPTION
**Pull request by crftwrk**
This PR removes 3 more WC templates in checkout according to WC 8.1 which comes on Tuesday next week https://developer.woocommerce.com/2023/08/29/woocommerce-8-1-0-beta-1-released/ and improves the form validation. Tested, works fine and is already live on bootscore.me. Not each file must be reviewed, the overall check is enough.

Checkout shortcode will be replaced by checkout block in WooCommerce in November https://developer.woocommerce.com/2023/08/18/cart-and-checkout-blocks-becoming-the-default-experience/. So, we can delete file in v6.

| Before  | After |
| ------------- | ------------- |
| before  | after  |

@justinkruit if you like it, merge it ;-)

Closes https://github.com/bootscore/bootscore/issues/343

### CODE REVIEW

**Comment by justinkruit** [comment]
> Checkout shortcode will be replaced by checkout block in WooCommerce in November https://developer.woocommerce.com/2023/08/18/cart-and-checkout-blocks-becoming-the-default-experience/. So, we can delete file in v6.

I'm having my doubts about that. I like the possibility of changing the layout, and I think a lot of developers do so. As far as my research goes, the blocks are way more limited to code editing. So my opinion is to keep the shortcode edits we've made.

**Comment by justinkruit** [comment]
> Totally agree, but I think we should provide support to the Blocks step-by-step. It seems to be not an impossible thing.

Also agree on that, but maybe keep both supported? The shortcode is far from deprecated, it's just not the default anymore. I think it's best to keep the support in the theme, and focus on how to style both the shortcodes and blocks together.

**Comment by crftwrk** [comment]
> Also agree on that, but maybe keep both supported?

You're right

**Comment by justinkruit** [comment]
Then we agree on that 😉

**Review by justinkruit — APPROVED** [review]
Then I'll now stop keeping this PR hostage 😂
All seems good to me 👍

**Pull request merged**
