### PR TITLE
Responsive offcanvas sidebar

### PR DESCRIPTION
**Pull request by crftwrk**
This PR adds a responsive offcanvas sidebar using the 5.2.0 component https://getbootstrap.com/docs/5.2/components/offcanvas/#responsive.

Demo: https://dev.bootscore.me/2012/01/07/template-sticky/, resize browser window to phone size.

Closes https://github.com/bootscore/bootscore/issues/117

Edit: This works for all sidebar-left and sidebar-right templates.

### CODE REVIEW

**Comment by justinkruit** [comment]
Maybe rename the button? I feel like "Sidebar" is clear for us, but an average user wouldn't know what a sidebar is, especially since it's not actually on the side anymore, but in an offcanvas. Maybe something like "Open side menu"?

**Comment by crftwrk** [comment]
Changed button name

**Review by justinkruit — APPROVED** [review]
Looks good! This responsive offcanvas is such a nice addition, as writing such a responsive sidebar is often not fun at all.

**Comment by crftwrk** [comment]
Cool, you want to merge?

**Comment by justinkruit** [comment]
Sure!

**Pull request merged**
