### PR TITLE
add WooCommerce quantity input - + fontawesome buttons

### PR DESCRIPTION
**Pull request by Lo1176**
Feature to change originals quantity arrows to "- +" fontawesome buttons.
Please take the time to double check that ;)

### CODE REVIEW

**Comment by crftwrk** [comment]
Thank you! A few change requests:

WooCommerce scripts and styles should be strictly separated from default bootscore files:

- All SCSS for WooCommerce are in subfolder `scss/bootscore_woocommerce`
- All SCSS import for WooCommerce are in file `_bscore_woocommerce.scss`
- All JS for WooCommerce are in `woocommerce/js/woocommerce.js`
- All functions for WooCommerce are in `woocommerce/woocommerce-functions.php`

### Better

- Rename `_qty_btn.scss` to `_wc_qty_btn.scss`
- Store file in `css/scss/bootscore_woocommerce/_wc_qty_btn.scss`
- `@import` file in `css/scss/_bscore_woocommerce.scss`
- jQuery please in `woocommerce/js/woocommerce.js`

WooCommerce is deactivated by default and can be activated by using the bootcommerce child. WC scripts styles and scripts should only be loaded if this child is active. For this it's important not to mix default and WC files.

Thanks 😉

**Comment by Lo1176** [comment]
Hi [crftwrk](https://github.com/crftwrk)

Thanks for your comments. Now, everything must be as it should be, well organized. Thanks to you.

- Rename _qty_btn.scss to _wc_qty_btn.scss
- Store file in css/scss/bootscore_woocommerce/_wc_qty_btn.scss
- @import file in css/scss/_bscore_woocommerce.scss
- jQuery please in woocommerce/js/woocommerce.js

**Comment by crftwrk** [comment]
I'm not really happy about the size and behaviour. Think classes do not work, because quantity in single-product is different from quantity in cart-page. We should use input-group instead classes and add some custom SCSS. Fontawesome seems a bit too much for me and we should keep the WC hooks.

Played a bit around, please check https://dev.bootscore.me/product/cheap-product/ and cart-page as well. Looks good on every device.


### quantity-input.php
```php
...
<div class="quantity input-group">
  <?php do_action( 'woocommerce_before_quantity_input_field' ); ?>
  <button type="button" class="input-group-text qty_button minus">-</button>
  <label class="screen-reader-text" for="<?php echo esc_attr( $input_id ); ?>"><?php esc_html_e( 'Quantity', 'woocommerce' ); ?></label>
  <input type="number" id="<?php echo esc_attr( $input_id ); ?>" class="input-text qty text form-control" step="<?php echo esc_attr( $step ); ?>" min="<?php echo esc_attr( $min_value ); ?>" max="<?php echo esc_attr( 0 < $max_value ? $max_value : '' ); ?>" name="<?php echo esc_attr( $input_name ); ?>" value="<?php echo esc_attr( $input_value ); ?>" title="<?php echo esc_attr_x( 'Qty', 'Product quantity input tooltip', 'woocommerce' ); ?>" size="4" pattern="<?php echo esc_attr( $pattern ); ?>" inputmode="<?php echo esc_attr( $inputmode ); ?>" aria-labelledby="<?php echo esc_attr( $labelledby ); ?>" />
  <button type="button" class="input-group-text qty_button plus">+</button>
  <?php do_action( 'woocommerce_after_quantity_input_field' ); ?>
</div>
...
```

### Custom SCSS
```scss
// Single product page
.woocommerce {
  div.product form.cart {
    display: flex;

    div.quantity {
      float: none;
      margin-right: 1rem;
      width: 140px; // Fixed width for input group
    }
  }

  // Width input field
  .quantity .qty {
    width: 2rem;
  }

  // Add to cart button
  div.product form.cart .btn {
    flex-grow: 1;
  }
}


// Cart page
.woocommerce-cart-form .product-quantity .quantity {
  width: 140px; // Fixed width for input group
}

// Woocommerce breakpoint is at 769px
@media (max-width: 768px) {
  .woocommerce-cart-form .product-quantity .quantity {
    margin-left: auto;
  }
}
```

Do you agree?

**Comment by Lo1176** [comment]
Totally !
You're right 👍

**Comment by crftwrk** [comment]
Cool, do you want to change this?

**Comment by Lo1176** [comment]
Basti, I have some weird issues with this new bootscore 5.2
It is a great idea to separate WooCommerce scripts and styles but when I do changes it won't compile anymore my scss changes ...
Do you have the same issues ?

**Comment by crftwrk** [comment]
Yes, subfolders won't compile automatically. Add `define('WP_ENVIRONMENT_TYPE', 'development');` to wp-config.php. Now scssphp compiles on every pageload.

Check here https://github.com/bootscore/bootscore/issues/40

**Comment by Lo1176** [comment]
ok thanks, it's working well.

I add this to your code :
```scss
// woocommerce breakpoint is at 992px
@media (max-width: 991px) {
  .woocommerce div.product form.cart {
    flex-wrap: wrap;
    div.quantity {
      margin-right: auto;
      width: 100%;
      margin-bottom: 0.5rem;
    }
  }
}
```

**Comment by crftwrk** [comment]
```
// woocommerce breakpoint is at 992px
@media (max-width: 991px) {
  .woocommerce div.product form.cart {
    flex-wrap: wrap;
    div.quantity {
      margin-right: auto;
      width: 100%;
      margin-bottom: 0.5rem;
    }
  }
}
```
This will make the input very large on mobile devices. Better to do this in child.

> Basti, I added the js in woocommerce.js but it doesn't take it into consideration. The - and + are not working with bootscore 5.2

let me check

**Comment by Lo1176** [comment]
> This will make the input very large on mobile devices. Better to do this in child.

Not at all, it's just to compensate for the shape of the buttons on the ipad and others.
Capture d’écran 2022-02-10 à 12 06 14

to this :
Capture d’écran 2022-02-10 à 12 07 09

In mobile first you get this :
Capture d’écran 2022-02-10 à 12 08 16

What do you think ?

**Comment by crftwrk** [comment]
Yes, that's because the sidebar. What's about this?

```scss
// Put qty-btn and add to cart on two lines
// woocommerce breakpoint is at 992px
@media (min-width: 769px) and (max-width: 991px) {
  .woocommerce div.product form.cart {
    flex-wrap: wrap;
    div.quantity {
      margin-right: auto;
      width: 100%;
      margin-bottom: 0.5rem;
    }
  }
}
```

We can show them in two lines only on screen sizes between 769px and 991px. If you agree, I'm in ;-)

Your js with 5.2 works now?

**Comment by Lo1176** [comment]
Exactly
I was doing this
```scss
// Woocommerce breakpoint is at 769px
@media (max-width: 768px) {
  .woocommerce-cart-form .product-quantity .quantity {
    margin-left: auto;
  }
  .woocommerce div.product form.cart {
    div.quantity {
      margin-right: 1rem;
      width: 40%;
      margin-bottom: 0;
    }
  }
}
```
for this :
Capture d’écran 2022-02-10 à 12 27 19

But your code is smarter

**Comment by crftwrk** [comment]
> But your code is smarter

If you agree I'm happy if you change this.

If finally you agree with everything I will merge this supercool thing 🤩

**Comment by Lo1176** [comment]
It's perfect

**Review by crftwrk — APPROVED** [review]
Supercool! Thank you for this!

**Pull request merged**
