### PR TITLE
Filter updates to Ajax Off-Canvas Cart/Basket

### PR DESCRIPTION
**Pull request by hsankala**
Concerning https://github.com/orgs/bootscore/discussions/883

### **1. Product Excerpt Display**  
- **Current Behavior**: The cart menu includes truncated product excerpts, which sometimes contain rendered HTML tags like `<tables>`.  
- **Concerns**:  
  - This makes the menu feel a bit busy, particularly with verbose descriptions or headings.  
  - The truncated text doesn’t seem to add much value in this context.  
- **Suggestion**: Introduce a **filter** to allow users to **disable the product excerpt** in the cart menu for a cleaner and simpler layout.  

---

### **2. Product Titles**  
- **Current Behavior**: Product titles are limited by a `text-truncate` CSS class.  
- **Issue**: This truncation can cut off important information, reducing the cart's usability.  
- **Observation**: In version 5, full product titles were displayed, which provided a better user experience.  
- **Suggestion**: Apply a **filter** or **add a CSS ID to the anchor tag** for the product name, so it can be easily targeted with CSS. This would allow users to override the text truncation CSS rules and display the full product title in the cart.

---

### **3. Stock Level Notifications**  
- **Current Behavior**: The "Only X left in stock" notification is always displayed in the cart menu.  
- **Concerns**: While helpful, this feature might not be desirable for all users.  
- **Suggestion**: Introduce a **filter** to **enable or disable the stock level notification** for more customization flexibility.  

---

### **Summary of Proposed Enhancements**  
To make the cart/basket menu more customisable, I suggest adding:  
1. **A filter to disable the product excerpt display.**  
2. **A filter to control the truncation of product titles.**  
3. **A filter to enable/disable the stock level notification.**

### CODE REVIEW

**Comment by crftwrk** [comment]
Hi Hefin,

thank you. This PR goes to main branch instead to https://github.com/bootscore/bootscore/tree/Add-more-filters and I'm not able to change this here because this branch has updated files since your last PR. Can you please check this?

Thanks Basti

**Comment by hsankala** [comment]
When I create a Pull request from my Forked Bootscore repo I get this:

image

And I'm not sure what to set it too.

Not really sure how to fix so I've closed this 'Pull Request', now.  Don't want to give @crftwrk any more of a headache.   If I can help or if you want me to open another PR let me know , but I'd probably need to be told how best to open a empty pull request for these changes.

**Comment by crftwrk** [comment]
Yes, that‘s because your forked branch is not up-to-date anymore and this file has been changed since your last PR. At best, you delete your fork and then fork a fresh version again.

**Comment by hsankala** [comment]
OK, I've forked the latested Bootscore Repo. And recreated the PR with the following settings, hope this is right...

image

**Pull request closed without merging**
