### PR TITLE
5.2.3.2

### PR DESCRIPTION
**Pull request by crftwrk**
- WooCommerce 7.4 templates has been updated already here https://github.com/bootscore/bootscore/pull/401
- Tested, works fine and is already live on bootscore.me. 

There is already a drafted release. @justinkruit if you agree, I'm happy when you just hit the merge button and publish release.

### CODE REVIEW

**Comment by justinkruit** [comment]
The change in #401 also includes the fix of #400?

**Comment by crftwrk** [comment]
> The change in https://github.com/bootscore/bootscore/pull/401 also includes the fix of https://github.com/bootscore/bootscore/pull/400?

Yes, a bit smarter.

**Comment by justinkruit** [comment]
Great 👍

**Review by justinkruit — DISMISSED** [review]
All looks good, including changes in #401.

Will merge and release this afternoon/evening!

**Comment by justinkruit** [comment]
Well, uhm.. a reminder has been set for the morning!! 😂
_I knew I forgot something..._

**Pull request merged**
