### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by justinkruit**
- Added a products class to the wc loop start
- Replaced mb-4 with gutters

@crftwrk If you got any small changes you wanna do, maybe this is a nice moment? :D You could add to the PR.

Closes https://github.com/bootscore/bootscore/issues/491

### CODE REVIEW

**Review by crftwrk — APPROVED** [review]
For now, I have no idea for small changes anymore ;-)

**Comment by crftwrk** [comment]
Should I merge or we just want to wait until tomorrow? Maybe there is one more small fix coming this night.

**Comment by justinkruit** [comment]
Maybe just merge just before the release.

**Comment by crftwrk** [comment]
We should release it tomorrow

**Comment by crftwrk** [comment]
Did some small changes as well. Think we should merge and go.

**Review by crftwrk — APPROVED** [review]

**Pull request merged**
