### PR TITLE
Fix redirect checkout if cart is empty

### PR DESCRIPTION
**Pull request by crftwrk**
This fixes a bug that has been overlooked in https://github.com/bootscore/bootscore/pull/755. In my point of view this is an edge case and can be solved in the next maintaining release. This bug happens if you are on checkout page and do nothing more a few days until WC empties the cart by itself by removing the cookie.

Steps to reproduce: 

- Open https://dev.bootscore.me/shop/ twice in two tabs
- Add a product and go to checkout
- Switch to the other tab and remove product from the cart
- Go back to the checkout tab and reload the page

As a result, page stucks because checkout, if cart is empty, redirects to cart page by WC and cart page redirects to checkout by us.

This PR checks if cart is empty and redirects checkout to shop page instead.

### CODE REVIEW

**Comment by justinkruit** [comment]
Want to do this before #814 ?

**Comment by crftwrk** [comment]
> Want to do this before https://github.com/bootscore/bootscore/pull/814 ?

We can do it now or we can do it in the next maintaining release. So we have something to do in future and can test the auto-updater as well. Both is fine for me. Added a description to describe and reproduce the bug.

**Comment by justinkruit** [comment]
Are we sure we want a redirect to the store in this case? Maybe it's best to just skip the redirect, so you at least see the message of "Empty cart".

**Comment by crftwrk** [comment]
> Maybe it's best to just skip the redirect, so you at least see the message of "Empty cart".

Good idea! See https://github.com/bootscore/bootscore/pull/822

**Pull request closed without merging**
