### PR TITLE
Add an includable font awesome short code function

### PR DESCRIPTION
**Pull request by kreincke**
as discussed this morning: 

- inc now contains a file fa-shortcode.php containing the code [as literally been tested this afternoon]
- functions.php contains the respective include statement

Feel free to find a better integration

### CODE REVIEW

**Comment by crftwrk** [comment]
This is a good one 👍, but:

We do not need an additional file for this snippet. I understand, because it's about the license thing https://github.com/bootscore/bootscore/pull/365. But if we start to add a new file for every tiny change, new contributors will do the same and theme get messed up.

Better to add this in `functions.php` direct below the Fontawesome preload snipped in line `301` to keep all Fontawesome related scripts in one place.

Do you agree?

**Comment by kreincke** [comment]
I totally agree! I hesitated to insert it into functions.php directly because I did not know whether you want to have in the main functions.php (wherein I would put it) or int the template for the child themes. 
Kindly regards kr
(BTW: So, in this case it was not a matter of the SPDX licensing headers ;-) But that has its advantages. By this statement, you know that I gave you the code under the terms of the MIT license. Informally, we knew that all the time. But now it is explicitly done. And provable ;-) )

**Comment by crftwrk** [comment]
Want to change this?

**Comment by kreincke** [comment]
Sorry - I did not see this ask. So, what's the best way for you? Shall I wait until 5.2.3.2 is out and reset the pull request to that base, or shall I do it now?

**Comment by kreincke** [comment]
Yes, please do so. I will close all my clones too. And I will restart  the pr this weekend

**Pull request closed without merging**
