### PR TITLE
Prepare pagination for translation and use 2 spaces instead of tab for indentation

### PR DESCRIPTION
**Pull request by patrickcognitif**

### CODE REVIEW

**Comment by crftwrk** [comment]
May I ask what this PR exactly does?

One more thing for the credits: https://github.com/patchampoux and https://github.com/patrickcognitif is both you? Which profile should be linked in credits?

**Comment by patrickcognitif** [comment]
Hi Basti!

The PR registers the strings contained in the_pagination() for translation.

Yes both accounts are mine, one is my personal, the other for my company. You can link to patrickcognitif in the credits.

Thanks and have a nice day!

Patrick Champoux

Développeur Web + cofondateur

 <https://cognitif.ca/>
Téléphone : 819 498-8377 #101 <tel:+18194988377>
Sans frais : 1 866 539-6476 #101 <tel:+18665396476>             
710 Notre-Dame sud
Louiseville (Québec)  J5V 1Y9

cognitif.ca <https://cognitif.ca/>       	
 <https://www.facebook.com/cognitifweb>
 <https://www.instagram.com/studio.cognitif/>
 <https://www.behance.net/cognitif>

**Comment by crftwrk** [comment]
Yes, but you did it already here https://github.com/bootscore/bootscore/pull/404? However, this PR has conflict because https://github.com/bootscore/bootscore/pull/404 is merged already. Want to create a new one?

**Comment by patrickcognitif** [comment]
Yes but this one uses 2 spaces instead of tabs, as requested by crftwrk.

Patrick Champoux

Développeur Web + cofondateur

 <https://cognitif.ca/>
Téléphone : 819 498-8377 #101 <tel:+18194988377>
Sans frais : 1 866 539-6476 #101 <tel:+18665396476>             
710 Notre-Dame sud
Louiseville (Québec)  J5V 1Y9

cognitif.ca <https://cognitif.ca/>       	
 <https://www.facebook.com/cognitifweb>
 <https://www.instagram.com/studio.cognitif/>
 <https://www.behance.net/cognitif>

**Comment by crftwrk** [comment]
https://github.com/bootscore/bootscore/pull/404 had 2 spaces as well and is already merged. What‘s with this PR here, can we close it?

**Comment by patrickcognitif** [comment]
You can close it then. Might be a mistake on my part.

Patrick Champoux

Développeur Web + cofondateur

 <https://cognitif.ca/>
Téléphone : 819 498-8377 #101 <tel:+18194988377>
Sans frais : 1 866 539-6476 #101 <tel:+18665396476>             
710 Notre-Dame sud
Louiseville (Québec)  J5V 1Y9

cognitif.ca <https://cognitif.ca/>       	
 <https://www.facebook.com/cognitifweb>
 <https://www.instagram.com/studio.cognitif/>
 <https://www.behance.net/cognitif>

**Pull request closed without merging**
