### PR TITLE
Feature breadcrumbs

### PR DESCRIPTION
**Pull request by sean-au**
Update standard and WC breadcrumbs to Bootstrap 5.2 spec.
Divider can now be styled with CSS :before

### CODE REVIEW

**Comment by crftwrk** [comment]
Thank you for this PR. Yes, it's still the breadcrumb from v4 version, an update to v5 is absolutely a good thing. However, breadcrumb is wrapped in a horizontal scroller on mobile devices. I changed some classes in your function and added some css to keep this feature. Users can simply disable this by removing the classes from the wrapper.

Please switch to mobile view: 

- https://dev.bootscore.me/2009/07/02/edge-case-many-categories/
- https://dev.bootscore.me/product/beanie/

Let me know what you think.  

### Breadcrumb
```php
if (!function_exists('the_breadcrumb')) :
function the_breadcrumb()
{
  if (!is_home()) {
    echo '<nav aria-label="breadcrumb" class="breadcrumb-scroller mb-4 mt-2 py-2 px-3 bg-light rounded">';
    echo '<ol class="breadcrumb mb-0">';
    echo '<li class="breadcrumb-item"><a href="' . home_url() . '">' . '<i class="fa-solid fa-house"></i>' . '</a></li>';
    // display parent category names with links
    if (is_category() || is_single()) {
      $cat_IDs = wp_get_post_categories(get_the_ID());
      foreach ($cat_IDs as $cat_ID) {
        $cat = get_category($cat_ID);
        echo '<li class="breadcrumb-item"><a href="' . get_term_link($cat->term_id) . '">' . $cat->name . '</a></li>';
      }
    }
    // display current page name
    if (is_page() || is_single()) {
      echo '<li class="breadcrumb-item active" aria-current="page">' . get_the_title() . '</li>';
    }
    echo '</ol>';
    echo '</nav>';
    echo '</nav>';
  }
}
add_filter('breadcrumbs', 'breadcrumbs');
endif;
```

### WC Breadcrumb

```php
if (!function_exists('bs_woocommerce_breadcrumbs')) :
  add_filter('woocommerce_breadcrumb_defaults', 'bs_woocommerce_breadcrumbs');
  function bs_woocommerce_breadcrumbs() {
    return array(
      'delimiter'   => '',
      'wrap_before' => "<nav aria-label='breadcrumb' class='wc-breadcrumb breadcrumb-scroller mb-4 mt-2 py-2 px-3 bg-light rounded'>
      <ol class='breadcrumb mb-0'>",
      'wrap_after'  => '</ol>
      </nav>',
      'before'      => '<li class="breadcrumb-item">',
      'after'       => '</li>',
      'home'        => _x('Home', 'breadcrumb', 'woocommerce'),
    );
  }
endif;
```

### SCSS

https://github.com/bootscore/bootscore/blob/main/scss/bootscore/_breadcrumb.scss 

```scss
@include media-breakpoint-down(lg) {
  .breadcrumb-scroller {
    white-space: nowrap;
    overflow-x: scroll;
    overflow-y: hidden;
    -ms-overflow-style: none;
    overflow: -moz-scrollbars-none;
    scrollbar-width: none;

    &::-webkit-scrollbar {
      display: none;
    }

    .breadcrumb {
      flex-wrap: nowrap;
    }

    .breadcrumb-item {
      &.active {
        padding-right: $spacer;
      }

      + .breadcrumb-item::before {
        float: none;
      }
    }
  }
}
```

New file `scss/bootscore_woocommerce/_wc_breadcrumb.scss`

```scss
.wc-breadcrumb .breadcrumb-item:last-child {
  color: var(--bs-breadcrumb-item-active-color);
  padding-right: $spacer;
}
```

**Comment by sean-au** [comment]
Looking great.

I would personally leave off "background-light rounded" as it has no effect
with the current background settings, however will be a bit of work to find
and fix if the background color is changed in a child theme.

**Comment by crftwrk** [comment]
@sean-au cool, want to do quickly this changes?

**Comment by sean-au** [comment]
Sure, but may not be til tomorrow as I'm off grid

**Comment by sean-au** [comment]
I consolidated the margin and padding classes, used p-3 for the NAV and didn't override its child's mb-3 with m-0, has the same results but easier to target and override with CSS. 

I tested and I can't see that the wc-breadcrumb class is working, but maybe I am looking in the wrong place

**Comment by crftwrk** [comment]
https://dev.bootscore.me/product/beanie-with-logo/

Default breadcrumb
Bildschirmfoto 2022-10-06 um 13 21 44

WC breadcrumb with `wc-breadcrumb` css
Bildschirmfoto 2022-10-06 um 13 22 04

WC breadcrumb without `wc-breadcrumb` css
Bildschirmfoto 2022-10-06 um 13 22 24

**Review by crftwrk — APPROVED** [review]
Merge this now to have no complications with your other PR's. We should keep the bg-light class because breadcrumb has the same style as before. I'll do it in a second PR.

**Pull request merged**
