### PR TITLE
Use function for sidebar col width and responsive offcanvas

### PR DESCRIPTION
**Pull request by crftwrk**
Think this PR speaks for itself. Change the entire main/sidebar columns and breakpoints in one file.

@justinkruit if you like it, merge it. Are you able to publish a release next Monday?

### CODE REVIEW

**Comment by justinkruit** [comment]
Maybe instead of functions, we should use filters/actions?

**Comment by justinkruit** [comment]
Sure! Just quickly wrote this for the sidebar.php

```
<div class="<?= apply_filters('bootscore_sidebar_cols', 'col-md-4 col-lg-3'); ?> order-first order-md-last">
```

With this people can do the following in their child theme:
```php
add_filter('bootscore_sidebar_cols', 'bootscore_sidebar_cols_function');
function bootscore_sidebar_cols_function($string) {
  return 'col-lg-4';
}
```

Which will then override `col-md-4 col-lg-3`.

Maybe we should do this too with the containers?

**Comment by crftwrk** [comment]
The thing is that we **_have_** to do this with containers and main-col as well. Means that we must edit all files again, rewrite the docs and keep existing functions in the trash file to not create breaking changes. I'm fine with the functions right now and we can adress this to v6?

**Comment by justinkruit** [comment]
Sure, we can make a big breaking change for this with v6. Seems like a good plan.

**Review by justinkruit — APPROVED** [review]
Looks fine to me.
Honestly looking forward to possibly change everything with filters and make an even more streamlined process 😁

**Pull request merged**
