### PR TITLE
5.2.3.0

### PR DESCRIPTION
**Pull request by crftwrk**
Update to Bootstrap 5.2.3. Tested, works fine and is already live on bootscore.me. There is already a drafted release. @justinkruit if you agree, I'm happy when you just hit the merge button and publish release.

### CODE REVIEW

**Comment by justinkruit** [comment]
Gonna try to make this release tomorrow

**Review by justinkruit — DISMISSED** [review]

**Comment by crftwrk** [comment]
We can also wait until 13th December. There is a WC update scheduled with some template changes https://developer.woocommerce.com/2022/11/23/woocommerce-7-2-beta-1/

**Comment by justinkruit** [comment]
Oh that may actually be smarter, as BS 5.2.3 isn't _that_ special

**Comment by crftwrk** [comment]
Updated WC 7.2.0 templates. Tested, works fine and is already live on bootscore.me. 

Quantity input is now visible on each product page, even product is out of stock or settings are limit to sell only 1 item. But amount in quantity input is not editable. Check here https://bootscore.me/shop/plugins/dark-mode/bs-dark-mode/. This is done by updated `quantity-input.php` https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/global/quantity-input.php

@justinkruit if you agree, I'm happy when you hit the merge button and publish the release.

**Review by justinkruit — APPROVED** [review]
All looks good to me 👍

**Pull request merged**
