### PR TITLE
Enable cross sell products

### PR DESCRIPTION
**Pull request by crftwrk**
Closes https://github.com/bootscore/bootscore/issues/542

### Test

- Go to shop https://dev.bootscore.me/shop/ and add "Album" and "Beanie with Logo" to the cart
- Go to cart page

cross sell

@justinkruit if you like it, merge it.

### CODE REVIEW

**Comment by justinkruit** [comment]
Maybe there is a different way to do this, instead of overriding the col sizes with css which I personally don't find very clean.

Maaaayyybbee we can make the cols a filter? And write a check if it's the cross sells list, and then override the cols.

**Comment by crftwrk** [comment]
> Maaaayyybbee we can make the cols a filter? And write a check if it's the cross sells list, and then override the cols.

Of course, any idea?

**Comment by justinkruit** [comment]
@crftwrk I've added 2 commits to the PR, which changes the cols into a filter and makes it 6 cols wide on the cart page.

**Comment by crftwrk** [comment]
Much more better, thank you!

**Review by justinkruit — APPROVED** [review]

**Pull request merged**
