### PR TITLE
Change button class for payment-methods

### PR DESCRIPTION
**Pull request by Lo1176**
Hi !
Can you change line 79 class "button" to "btn btn-outline-primary" to have the same style than the other buttons ?

### CODE REVIEW

**Comment by crftwrk** [comment]
👍

**Review by crftwrk — APPROVED** [review]
👍

**Review by justinkruit — APPROVED** [review]
All seems fine

**Comment by Lo1176** [comment]
Maybe it is the same thing in thankyou.php line 35 and 37
and in payment.php line 46

**Comment by crftwrk** [comment]
> Maybe it is the same thing in thankyou.php line 35 and 37
and in payment.php line 46

We're happy if you create a new Pull request them :-)

**Comment by Lo1176** [comment]
No problems ! ;)

**Pull request merged**
