### PR TITLE
5.2.0.0 release

### PR DESCRIPTION
**Pull request by crftwrk**
Closes https://github.com/bootscore/bootscore/issues/140

This PR ships the 5.2.0.0 release. Tested and works fine. There is one issue with pagination component, all items have border-radius, hotfixed it here https://github.com/bootscore/bootscore/commit/16eb38e8f6452df919d5ef9d0c0339e408400405

@justinkruit If you agree, I'm happy when you just hit the merge button. There is a drafted release as well, but we have to choose a new tag according to https://github.com/bootscore/bootscore/issues/165. I'm tomorrow not on my computer but still have to write some update guides because too many things changed here. I suggest to release on Thursday July 21 and it will be a honor for me when you release it.

### CODE REVIEW

**Comment by justinkruit** [comment]
Would it be alright if we set the release for tomorrow, July 22? I'd like to fix the pagination bug if possible before the release, but I didn't have the time yesterday.

**Comment by crftwrk** [comment]
Ok, let's do it tomorrow, thank you.

**Comment by justinkruit** [comment]
Alright, after testing it seems like this may be a scssphp problem, and not Bootstrap. Specifically here: https://github.com/twbs/bootstrap/blob/edf9c40956d19e6ab3f9151bfe0dfac6be06fa21/scss/_pagination.scss#L78
The `if` goes wrong somehow, and it falls back on the `else` which has a border radius on each item.

**Comment by crftwrk** [comment]
Ok, we leave it as it is and release tomorrow? We can look later for a better solution.

**Pull request merged**
