### PR TITLE
Fix IE warning

### PR DESCRIPTION
**Pull request by Axos11**
Translation is included and therefore I placed the .js in an extra file.

### CODE REVIEW

**Comment by justinkruit** [comment]
Actually, the extra js file isn't needed, neither do you need to add the footer function. You can just keep the js in the original file, and put the localize script directly below the enqueue.

**Comment by Axos11** [comment]
Could you give me the example how to leave the .js in theme.js and then access it with wp_localize_script?

The add_action( 'wp_footer', 'add_localization'); was just added because the translation didn't work without it with the approach i took.

**Comment by justinkruit** [comment]
I've made some changes so the js can be in theme.js, and the translations load correctly. I also went ahead and made the i18n strings to how WordPress likes them.

**Comment by crftwrk** [comment]
Doesn't show any warning in IE 11 on my machine.

**Comment by Axos11** [comment]
didn't work on my pc either, reason was a syntax error in theme.js which broke the whole function in IE. 

It seems to be working now except the translation of the 2nd line ("Please use a ...") that phrase stays in english.

**Comment by justinkruit** [comment]
> didn't work on my pc either, reason was a syntax error in theme.js which broke the whole function in IE.

Oops, apparently when I format the file, it wants to add a comma there. Need to debug on my side why it's doing that.

> It seems to be working now except the translation of the 2nd line ("Please use a ...") that phrase stays in english.

Unless translations have been added by condibutors, they default back to English.

**Comment by crftwrk** [comment]
Translation for
> Please use a modern and secure...

does still not work. 

But basically I agree with this. Maybe we can do some styling or using an alert popup instead of full-screen overlay in future. So users can see that there is something on the site but not displayed well because browsed by IE. Just an idea like the demo-shop-notice here https://demo.bootscore.me/bootcommerce-fashion-5/. But not important for me now.

Great job!

**Comment by Axos11** [comment]
The reason why I decided to go for a fullscreen solution is simply that the bootstrap .js files itself uses arrow functions (=>) which break the whole bootscore.bundle.min.js in the third line or so. So the page I am building right now looks really BROKEN. So I am not sure how "much" of the broken things you actually want to show the users.

**Review by crftwrk — APPROVED** [review]
As mentioned in previous comment, just an idea. I agree with this PR.

**Comment by Axos11** [comment]
> As mentioned in previous comment, just an idea. I agree with this PR, we can do changes later.

My reply was targeting the "later" ;) A bit more styling would be nice though. :)

**Comment by Axos11** [comment]
I did the german translation already. I added the string to the bootscore.pot file (in the last commit) and post the German translation right here. Don't know what the "right" way for the translation adaption would be so just tell me :)

#: functions.php:277
msgid "Please use a modern and secure web browser like <a href=\"%1$s\" target=\"_blank\">Mozilla Firefox</a>, <a href=\"%1$s\" target=\"_blank\">Google Chrome</a>, <a href=\"%1$s\" target=\"_blank\">Opera</a> or <a href=\"%1$s\" target=\"_blank\">Microsoft Edge</a> to display this site correctly."
msgstr "Bitte verwende einen aktuellen und sicheren Web Browser wie <a href=\"%1$s\" target=\"_blank\">Mozilla Firefox</a>, <a href=\"%1$s\" target=\"_blank\">Google Chrome</a>, <a href=\"%1$s\" target=\"_blank\">Opera</a> oder <a href=\"%1$s\" target=\"_blank\">Microsoft Edge</a> um diese Seite korrekt "
"anzuzeigen."

**Comment by crftwrk** [comment]
Suggest to do the translations in a second PR using [Loco translate](https://wordpress.org/plugins/loco-translate/) after this one has been merged. I can do that. If you agree with this, @justinkruit I'm happy if you press the merge button.

@Axos11 if you want to ship translations with this PR, here are the translation strings:

- Czech: `Prosíme, používejte moderní a bezpečný webový prohlížeč jako třeba <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> nebo <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> pro správné zobrazení stránky.`
- Dutch: `Gebruik alsjeblieft een moderne en veilige browser zoals <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> of <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> om dit correct weer te geven.`
- Dutch (Formal): `Gebruik alstublieft een moderne en veilige browser zoals <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> of <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> om deze website correct weer te geven.`
- French (France): `Veuillez utiliser un navigateur Web moderne et sécurisé tel que <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> ou <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> pour afficher ce site correctement.`
- German: `Bitte verwende einen modernen und sicheren Browser wie <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> oder <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> um diese Webseite korrekt darzustellen.`
- German (Formal): `Bitte verwenden Sie einen modernen und sicheren Browser wie <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> oder <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> um diese Webseite korrekt darzustellen.`
- Italian: `Ti consigliamo di utilizzare un browser moderno e sicuro come <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> o <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> per visualizzare correttamente il sito.`
- Polish: `Proszę używaj aktualnej i bezpiecznej przeglądarki internetowej, jak np.: <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> lub <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> żeby wyświetlić stronę poprawnie.`
- Portuguese (Brasil): `Use um navegador da web moderno e seguro como <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> ou <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> para exibir este site corretamente.`
- Russian: `Пожалуйста, используйте современный и безопасный веб-браузер, такой как <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> или <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> чтобы правильно отобразить этот сайт.`
- Spanish (Spain): `Por favor utiliza un navegador web moderno y seguro como <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> o <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> para mostrar este sitio correctamente.`
- Spanish (Colombia): `Utilice un navegador web moderno y seguro como <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> ó <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> para mostrar este sitio correctamente.`
- Spanish (Venezuela): `Utilice un navegador web moderno y seguro como <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> ó <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> para mostrar este sitio correctamente.`
- Swedish: `Vänligen använd en modern och säker webbläsare som <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> eller <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> för att visa den här webbplatsen korrekt.`
- Turkish: `Lütfen modern ve güvenli bir web tarayıcısı kullanın <a href="https://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a>, <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a>, <a href="https://www.opera.com/" target="_blank">Opera</a> veya <a href="https://www.microsoft.com/edge/" target="_blank">Microsoft Edge</a> bu siteyi doğru görüntülemek için.`

**Comment by crftwrk** [comment]
Changed the code a bit, translations works now as expected. We should merge this soon because I found a new site with this bug.

**Comment by Axos11** [comment]
i checked it again on my local installation. seems to work seamlessly.

**Comment by crftwrk** [comment]
The problem is this PR is old and now has conflicts in theme.js, header.php and header-woocommerce.php that need to be resolved. Can you update these files?

**Review by crftwrk — APPROVED** [review]
Finally we made it! 😉

**Pull request merged**
