### PR TITLE
5.2.2.0

### PR DESCRIPTION
**Pull request by crftwrk**
Surprisingly, there are no updated templates with WooCommerce 7. This PR submits only the theme version.

@justinkruit I'm happy if you just hit the merge button and as usual, there is a drafted release as well.

### CODE REVIEW

**Comment by justinkruit** [comment]
Alright if I take care of this in the weekend? Bit busy at work lately, so can't do it in between tasks currently 😇

**Comment by justinkruit** [comment]
@crftwrk Could you add #279 to the changelog? 😄

**Comment by crftwrk** [comment]
Done

**Comment by justinkruit** [comment]
I'll make the release tomorrow, didn't find time today

**Comment by justinkruit** [comment]
> I'll make the release tomorrow, didn't find time today

Well sh*t 😂

**Comment by crftwrk** [comment]
All good ;-)

**Review by justinkruit — APPROVED** [review]
All good to release 👍

**Pull request merged**
