### PR TITLE
Built a "filter" for terms.php

### PR DESCRIPTION
**Pull request by Axos11**
I wrapped the "getCorrectedTerms" around all hooks in that file (maybe no necessary), but it should only affect "correct" formated parts. (Tested with sendinblue newsletter plugin)

### CODE REVIEW

**Review by crftwrk — APPROVED** [review]
👍

**Comment by justinkruit** [comment]
May I ask what exactly the point is of this code? 

Also, I recommend to make the functions in the Woocommerce functions file, not in a template file.

**Comment by crftwrk** [comment]
This fixes hooked broken checkboxes in checkout. For example a sendinblue newsletter check.

I agree that it's better to solve that as a function instead of changing the WC template. Any idea?

**Comment by crftwrk** [comment]
Thought about it again. @justinkruit You're right, this file will too hard to maintain if WC updates the terms.php and we should keep template files as simple as possible. Was too fast pressing the merge button, my bad. I reverted this PR.

@Axos11 Are you able to remodel this filter using hooks and add it to woocommerce-functions.php?

**Comment by Axos11** [comment]
As far as i know, there are no filters for the hooks in terms.php. (if there are, just tell me and i will happily use them)
The issue came up with the modification of the terms.php file in the first place. So reverting the changes but still changing the "terms.php" file to a bootstrap syntax is not really an option in my oppinion.

You can move the 2 functions to a function.php file, thats not an issue at all. The only problem that still exists is, that there is not really any access to this content without modifying the terms.php file. (we could add a new filter for the used hooks there, but still. the terms.php file has to be edited and its basically the same :) )

**Comment by crftwrk** [comment]
Of course, this filter is absolutely neccessary. This is just some brainstorming how to add it more smooth. I'm a bit worry about maintaining this file. 

However, terms.php is edited already. So, more editing is ok. What's about your idea to add a new filter to file and do function in woocommerce-functions.php? A filter there is just one line of code in terms.php.

**Comment by Axos11** [comment]
If you just move the 2 functions "getCorrectedTerms()" and "captureHookOutput()" to the woocommerce-functions.php then you only have 3 changed lines of code which are :

- do_action('woocommerce_checkout_before_terms_and_conditions')
+ echo getCorrectedTerms(captureHookOutput('woocommerce_checkout_before_terms_and_conditions'));

- do_action('woocommerce_checkout_terms_and_conditions')
+ echo getCorrectedTerms(captureHookOutput('woocommerce_checkout_terms_and_conditions'));

- do_action('woocommerce_checkout_after_terms_and_conditions')
+ echo getCorrectedTerms(captureHookOutput('woocommerce_checkout_after_terms_and_conditions'));

The adaption to filters would be just a cosmetic thing. Actually the functionality would be just the same (at least i think so :) )

Ps: (I have to say, that i don't like the woocommerce approach there anyways. because they mix hooks with html code where only hooks would be as good :) )

**Comment by crftwrk** [comment]
Yes, think this is better. Keeping terms.php slim and put function to woocommerce-functions.php will be much more cleaner. Want to create a new PR?

> (I have to say, that i don't like the woocommerce approach there anyways. because they mix hooks with html code where only hooks would be as good :) )

I disagree with many things in WooCommerce ;-)

**Comment by justinkruit** [comment]
I think this would be the right approach, having the functions in woocommerce-functions.php. That way the terms.php is the most authentic, and should make updating it easier.

**Pull request merged**
