### PR TITLE
Fix: Tax include and exclude subtotal in WC Mini Cart.

### PR DESCRIPTION
**Pull request by anisur2805**
@crftwrk please review the changes and let me know the feedback.

### CODE REVIEW

**Comment by crftwrk** [comment]
@anisur2805 after changing the quantity, currency symbol and amount after comma disappears?


| After added to cart  | After changing the quantity |
| ------------- | ------------- |
| Bildschirmfoto 2024-03-20 um 17 55 35  | Bildschirmfoto 2024-03-20 um 17 55 46  |

**Comment by anisur2805** [comment]
@crftwrk after trying various methods, I've confirmed that everything is functioning correctly. Would you mind attempting the action again from incognito mode, just to be sure?

image

**Comment by crftwrk** [comment]
@anisur2805 tested it on different sites on different servers with different settings, but this happens to all of them.

Please check https://dev.bootscore.me/shop/

| After added to cart  | After changing the quantity |
| ------------- | ------------- |
| Bildschirmfoto 2024-03-21 um 10 33 06  | Bildschirmfoto 2024-03-21 um 10 33 20  |

**Comment by anisur2805** [comment]
@crftwrk here is the fix. Please review the changes.

Thank you.

**Review by crftwrk — APPROVED** [review]
Thank you! 🙏

**Pull request merged**
